plugins/auth/classes/class.rex_com_navigation.inc.php
plugins/auth_media/classes/class.rex_com_auth_media.inc.php
plugins/board/classes/class.rex_com_board.inc.php
plugins/comment/classes/class.rex_com_comment.inc.php

refs https://github.com/redaxo/redaxo4/pull/415

php7 fixes

---

plugins/auth/lib/ycom_auth.php

cookie_ttl --> auth_cookie_ttl
ycom ,login_field  --> ycom/auth, login_field

fixed config value names

---

pages/main.manual_form_change_password.inc

https://github.com/yakamara/redaxo_ycom/issues/175

Jetzt funktioniert der Beispielcode auch wieder

---

README.md

Auf Wunsch via Slack, damit klar ist, was das Addon kann. Bitte auch im Installer ausreichend beschreiben.

Feature-Beschreibung ergänzt

---

plugins/docs/docs/de_de/main_navi.md
plugins/docs/docs/de_de/trick.target_per_type.md
plugins/docs/docs/de_de/user.details.md

Die Navi-Unterteilung so verändert, dass sie sinnvoll ergänzt werden kann.

Navi, Nutzerdaten auslesen mit Beispielen

---

plugins/docs/docs/de_de/user.details.md

Beispiele für Gruppenberechtigungen

---

plugins/auth/lang/de_de.lang

ist sonst in den Meta Infos und YRewrite auch so beschriftet.

aktualisieren klein schreiben

---

plugins/docs/docs/de_de/main.register.md

Logout nach Registierungsbestätigung erwähnen

---

plugins/docs/docs/de_de/main.reset_password.md

Überprüfung ob User-E-Mail in Datenbank vorhanden, dann erst die E-Mail versenden
closes #247

Validierung Existenz der User-E-Mail

---

plugins/docs/docs/de_de/main.first-steps.md

Docs: Status entfernt

---

plugins/docs/docs/de_de/main.navigation.md

Korrekturen an #293 - weiß der Geier, warum hierfür ein neuer PR aufgemacht werden muss.
closes #293 
closes #292

Beispiel mit Offline-Kategorien ergänzen

---

plugins/docs/docs/de_de/main.login.md

Ergänzt um zwei Beispiele: Angemeldet bleiben und (bei Bedarf) autocomplete: off

Update main.login um Beispiele für den Login-Artikel

---

plugins/docs/docs/de_de/main.first-steps.md
plugins/docs/docs/de_de/main.settings.md

nur für SAML-Authentifizierung
closes #311

article_id_jump_not_ok erklären

---

plugins/docs/docs/de_de/main.change_password.md

Optional mittels Custom-Function wird zusätzlich das alte Passwort gecheckt.

Erweitert um Prüfung auf altes Passwort

---

plugins/docs/docs/de_de/main.change_password.md

Neues Passwort muss ungleich altem Passwort sein

Zusätzliche Validierung

---

composer.json
composer.lock
phpstan-baseline.neon
phpstan.neon.dist

make phpstan aware of dependent classes

Allow newer phpstan versions, cover more files

---

plugins/auth/lib/yform/value/ycom_auth_cas.php
plugins/auth/lib/yform/value/ycom_auth_oauth2.php
plugins/auth/lib/yform/value/ycom_auth_saml.php

rex_login::startSession verwenden

---

docs/03_login_logout_profile_register.md

Überflüssige Zeile herausgenommen wie in #441 beschrieben

Passwort Validierung rausgenommen

---

plugins/auth/lib/ycom_auth.php

history wird beim Userobjektaufruf deaktiviert

---

lib/ycom_user.php

fix isInGroup() Funktion

---

package.yml

Link auf docs nun fest. War falsch

---

install.php

Beim Install wird nach Passwort nun mit passendem Feld auch erstellt
